package lenguajes.proyectolenguajesydl;

import java.awt.event.*;
import lenguajes.proyectolenguajesydl.util.*;
import javax.swing.JTextPane;
import lenguajes.proyectolenguajesydl.analizadorlexico.AnalizadorLexico;
import lenguajes.proyectolenguajesydl.util.NumeroLinea;

/**
 *
 * @author yenni
 */
public class InterfazUsuario extends javax.swing.JFrame {

    NumeroLinea numEditor, numDisAnalisis;
    private final Archivo archivo;
    private final AnalizadorLexico lexer;
    private final Pintor pintor; 
    private final Graficador graficador;
    Reportero rep;
    /**
     * Creates new form InterfazUsuario
     */
    
    public InterfazUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
        initNumeracion();
        archivo = new Archivo();
        lexer = new AnalizadorLexico();
        pintor = new Pintor(lexer);
        rep = new Reportero();
        graficador = new Graficador();
        initStyle();
        initTable();
    }
    private void initNumeracion(){
        numEditor = new NumeroLinea(editor);
        scrollEditor.setRowHeaderView(numEditor);
        numDisAnalisis = new NumeroLinea(displayAnalisis);
        scrollDisAnalisis.setRowHeaderView(numDisAnalisis);
    }
    private void initStyle(){
        JTextPane txt = new JTextPane(pintor.getDefStyleDoc());
        String temp = editor.getText();
        editor.setStyledDocument(txt.getStyledDocument());
        editor.setText(temp);
    }
    private void initTable(){
        displayReporte.getTableHeader().setReorderingAllowed(false) ;
        displayReporte.addMouseListener(new MouseAdapter(){
            @Override
            public void mousePressed(MouseEvent mouseE){
                if(mouseE.getClickCount() == 1){
                    System.out.println(displayReporte.getValueAt(displayReporte.getSelectedRow(), 1));
                    String typeTkn = displayReporte.getValueAt(displayReporte.getSelectedRow(), 0).toString();
                    String lexema = displayReporte.getValueAt(displayReporte.getSelectedRow(), 2).toString();
                    graficador.graficar(typeTkn, lexema, "CurrentGraph");
                }
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bOpenFile = new javax.swing.JButton();
        bSave = new javax.swing.JButton();
        bSave1 = new javax.swing.JButton();
        bSave2 = new javax.swing.JButton();
        bSave3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        bClear = new javax.swing.JButton();
        bLexico = new javax.swing.JButton();
        scrollEditor = new javax.swing.JScrollPane();
        editor = new javax.swing.JTextPane();
        scrollDisAnalisis = new javax.swing.JScrollPane();
        displayAnalisis = new javax.swing.JTextPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayReporte = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(7, 7, 110));

        bOpenFile.setBackground(new java.awt.Color(7, 7, 110));
        bOpenFile.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        bOpenFile.setForeground(new java.awt.Color(255, 255, 255));
        bOpenFile.setText("Abrir archivo");
        bOpenFile.setFocusable(false);
        bOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOpenFileActionPerformed(evt);
            }
        });

        bSave.setBackground(new java.awt.Color(7, 7, 110));
        bSave.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        bSave.setForeground(new java.awt.Color(255, 255, 255));
        bSave.setText("Guardar");
        bSave.setFocusable(false);

        bSave1.setBackground(new java.awt.Color(7, 7, 110));
        bSave1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        bSave1.setForeground(new java.awt.Color(255, 255, 255));
        bSave1.setText("Generar Gráfica");
        bSave1.setFocusable(false);

        bSave2.setBackground(new java.awt.Color(7, 7, 110));
        bSave2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        bSave2.setForeground(new java.awt.Color(255, 255, 255));
        bSave2.setText("Ayuda");
        bSave2.setFocusable(false);

        bSave3.setBackground(new java.awt.Color(7, 7, 110));
        bSave3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        bSave3.setForeground(new java.awt.Color(255, 255, 255));
        bSave3.setText("Creditos");
        bSave3.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(bOpenFile, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bSave, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(bSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 504, Short.MAX_VALUE)
                .addComponent(bSave2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bSave3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bOpenFile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(bSave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bSave1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bSave2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bSave3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        bClear.setBackground(new java.awt.Color(7, 7, 110));
        bClear.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        bClear.setForeground(new java.awt.Color(255, 255, 255));
        bClear.setText("Limpiar");
        bClear.setFocusable(false);
        bClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClearActionPerformed(evt);
            }
        });

        bLexico.setBackground(new java.awt.Color(7, 7, 110));
        bLexico.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        bLexico.setForeground(new java.awt.Color(255, 255, 255));
        bLexico.setText("Analizador Léxico");
        bLexico.setFocusable(false);
        bLexico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLexicoActionPerformed(evt);
            }
        });

        scrollEditor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        editor.setBackground(new java.awt.Color(0, 0, 44));
        editor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        editor.setFont(new java.awt.Font("Dialog", 0, 17)); // NOI18N
        editor.setForeground(new java.awt.Color(0, 153, 204));
        editor.setCaretColor(new java.awt.Color(255, 255, 255));
        scrollEditor.setViewportView(editor);

        displayAnalisis.setEditable(false);
        displayAnalisis.setBackground(new java.awt.Color(0, 0, 44));
        displayAnalisis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        displayAnalisis.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        displayAnalisis.setForeground(new java.awt.Color(255, 255, 255));
        displayAnalisis.setCaretColor(new java.awt.Color(255, 255, 255));
        scrollDisAnalisis.setViewportView(displayAnalisis);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollEditor)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bClear, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bLexico, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(scrollDisAnalisis, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(scrollEditor, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bClear, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bLexico, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollDisAnalisis, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 840, 590));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        displayReporte.setBackground(new java.awt.Color(0, 0, 51));
        displayReporte.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        displayReporte.setForeground(new java.awt.Color(198, 198, 198));
        displayReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Token", "Patron", "Lexema", "L", "C"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        displayReporte.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        displayReporte.setFocusable(false);
        displayReporte.setGridColor(new java.awt.Color(0, 0, 0));
        displayReporte.setSelectionBackground(new java.awt.Color(0, 128, 201));
        displayReporte.setShowGrid(true);
        jScrollPane1.setViewportView(displayReporte);
        if (displayReporte.getColumnModel().getColumnCount() > 0) {
            displayReporte.getColumnModel().getColumn(0).setResizable(false);
            displayReporte.getColumnModel().getColumn(1).setResizable(false);
            displayReporte.getColumnModel().getColumn(2).setResizable(false);
            displayReporte.getColumnModel().getColumn(3).setResizable(false);
            displayReporte.getColumnModel().getColumn(3).setPreferredWidth(5);
            displayReporte.getColumnModel().getColumn(4).setResizable(false);
            displayReporte.getColumnModel().getColumn(4).setPreferredWidth(5);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 60, 510, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOpenFileActionPerformed
        editor.setText(archivo.readTextFile(archivo.getPath()));
    }//GEN-LAST:event_bOpenFileActionPerformed

    private void bLexicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLexicoActionPerformed
        lexer.analyzeAll(editor.getText());
        displayAnalisis.setText(lexer.getErrors());
        rep.setReporte(displayReporte, lexer);
    }//GEN-LAST:event_bLexicoActionPerformed

    private void bClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClearActionPerformed
        editor.setText("");
        displayAnalisis.setText("");
        rep.clearTable(displayReporte, true);
    }//GEN-LAST:event_bClearActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClear;
    private javax.swing.JButton bLexico;
    private javax.swing.JButton bOpenFile;
    private javax.swing.JButton bSave;
    private javax.swing.JButton bSave1;
    private javax.swing.JButton bSave2;
    private javax.swing.JButton bSave3;
    private javax.swing.JTextPane displayAnalisis;
    private javax.swing.JTable displayReporte;
    private javax.swing.JTextPane editor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane scrollDisAnalisis;
    private javax.swing.JScrollPane scrollEditor;
    // End of variables declaration//GEN-END:variables
}
