package lenguajes.proyectolenguajesydl;

import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import lenguajes.proyectolenguajesydl.lexer.Lexer;
import lenguajes.proyectolenguajesydl.parser.Parser;
import lenguajes.proyectolenguajesydl.parser.Registrador;
import lenguajes.proyectolenguajesydl.parser.SyntaxException;
import lenguajes.proyectolenguajesydl.util.Render;
import lenguajes.proyectolenguajesydl.util.Reportero;

/**
 *
 * @author yenni
 */
public class Reportes extends javax.swing.JFrame {

    private JFrame anterior;
    private Parser parser;
    private Lexer lexer;
    private Reportero reportero;
    private Registrador registrador;

    /**
     * Creates new form Reportes
     *
     * @param anterior
     * @param lexer
     * @param parser
     */
    public Reportes(JFrame anterior, Lexer lexer, Parser parser) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.anterior = anterior;
        this.lexer = lexer;
        this.parser = parser;
        this.reportero = new Reportero();
        this.registrador = parser.getRegistrador();
        ocultar(repFuncDisplay);
        ocultar(repSyntaxErrors);
        ocultar(repLexError);
        ocultar(repSymbolTBlock);
        ocultar(repSymbolT);
        ocultar(repListInstructions);
        

    }

    private void ocultar(JInternalFrame frame) {
        frame.setEnabled(false);
        frame.setVisible(false);
    }

    private void mostrar(JInternalFrame frame) {
        frame.setEnabled(true);
        frame.setVisible(true);
    }

    private void mostrarMssSyntaxError() {
        JOptionPane.showMessageDialog(null, """
                                            Se han encontrado errores de sintaxis, no se ha 
                                            podido generar el reporte, por favor corrige los 
                                            errores y vuelve a intentarlo""",
                "Errores sintacticos contrados",
                JOptionPane.ERROR_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        index = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        bTableSymbolG = new javax.swing.JButton();
        bTableSimbolB = new javax.swing.JButton();
        bInstructions = new javax.swing.JButton();
        bSyntaxError = new javax.swing.JButton();
        bLexErrors = new javax.swing.JButton();
        bMethodReport = new javax.swing.JButton();
        bAtrasGlobal = new javax.swing.JButton();
        repFuncDisplay = new javax.swing.JInternalFrame();
        panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        funReport = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        totalFuncDisplay = new javax.swing.JLabel();
        bAtras1 = new javax.swing.JButton();
        repSyntaxErrors = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        syntaxErrorsRep = new javax.swing.JTable();
        totalSyntaxErrors = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        repLexError = new javax.swing.JInternalFrame();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lexErrorRep = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        totalLexErrrors = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        repListInstructions = new javax.swing.JInternalFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listInstRep = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        repSymbolTBlock = new javax.swing.JInternalFrame();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        symbolTableBlocks = new javax.swing.JTable();
        bExitSTB = new javax.swing.JButton();
        repSymbolT = new javax.swing.JInternalFrame();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        symbolTable = new javax.swing.JTable();
        bExitTS = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        index.setVisible(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("GENERADOR DE REPORTES");

        bTableSymbolG.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        bTableSymbolG.setText("Tabla de simbolos global");
        bTableSymbolG.setFocusable(false);
        bTableSymbolG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTableSymbolGActionPerformed(evt);
            }
        });

        bTableSimbolB.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        bTableSimbolB.setText("Tabla de simbolos por bloque");
        bTableSimbolB.setFocusable(false);
        bTableSimbolB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTableSimbolBActionPerformed(evt);
            }
        });

        bInstructions.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        bInstructions.setText("Lista de instrucciones");
        bInstructions.setFocusable(false);
        bInstructions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInstructionsActionPerformed(evt);
            }
        });

        bSyntaxError.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        bSyntaxError.setText("Errores sintacticos");
        bSyntaxError.setFocusable(false);
        bSyntaxError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSyntaxErrorActionPerformed(evt);
            }
        });

        bLexErrors.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        bLexErrors.setText("Errores lexicos");
        bLexErrors.setFocusable(false);
        bLexErrors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLexErrorsActionPerformed(evt);
            }
        });

        bMethodReport.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        bMethodReport.setText("Reporte de metodos");
        bMethodReport.setFocusable(false);
        bMethodReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMethodReportActionPerformed(evt);
            }
        });

        bAtrasGlobal.setBackground(new java.awt.Color(255, 0, 0));
        bAtrasGlobal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bAtrasGlobal.setForeground(new java.awt.Color(255, 255, 255));
        bAtrasGlobal.setText("X");
        bAtrasGlobal.setFocusable(false);
        bAtrasGlobal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtrasGlobalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(bTableSymbolG, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bTableSimbolB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bInstructions, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(bMethodReport, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bLexErrors, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bSyntaxError, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(bAtrasGlobal)))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(bAtrasGlobal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bTableSymbolG, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(bTableSimbolB, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(bInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bMethodReport, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(bLexErrors, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(bSyntaxError, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout indexLayout = new javax.swing.GroupLayout(index.getContentPane());
        index.getContentPane().setLayout(indexLayout);
        indexLayout.setHorizontalGroup(
            indexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        indexLayout.setVerticalGroup(
            indexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indexLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(index, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        repFuncDisplay.setVisible(true);

        panel.setBackground(new java.awt.Color(204, 204, 204));
        panel.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("REPORTE DE FUNCIONES");

        funReport.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        funReport.setForeground(new java.awt.Color(0, 0, 0));
        funReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Linea", "Columna", "Nombre", "Parametros", "No. de veces llamada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        funReport.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(funReport);
        funReport.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (funReport.getColumnModel().getColumnCount() > 0) {
            funReport.getColumnModel().getColumn(0).setMinWidth(60);
            funReport.getColumnModel().getColumn(0).setPreferredWidth(60);
            funReport.getColumnModel().getColumn(0).setMaxWidth(60);
            funReport.getColumnModel().getColumn(1).setMinWidth(60);
            funReport.getColumnModel().getColumn(1).setPreferredWidth(60);
            funReport.getColumnModel().getColumn(1).setMaxWidth(60);
            funReport.getColumnModel().getColumn(4).setMinWidth(120);
            funReport.getColumnModel().getColumn(4).setPreferredWidth(120);
            funReport.getColumnModel().getColumn(4).setMaxWidth(120);
        }

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Total de funciones:");

        totalFuncDisplay.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        totalFuncDisplay.setForeground(new java.awt.Color(0, 0, 0));
        totalFuncDisplay.setText("0000");

        bAtras1.setBackground(new java.awt.Color(204, 0, 0));
        bAtras1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bAtras1.setText("X");
        bAtras1.setFocusable(false);
        bAtras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtras1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(281, 281, 281)
                        .addComponent(bAtras1))
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelLayout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(totalFuncDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAtras1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(totalFuncDisplay))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout repFuncDisplayLayout = new javax.swing.GroupLayout(repFuncDisplay.getContentPane());
        repFuncDisplay.getContentPane().setLayout(repFuncDisplayLayout);
        repFuncDisplayLayout.setHorizontalGroup(
            repFuncDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 894, Short.MAX_VALUE)
            .addGroup(repFuncDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        repFuncDisplayLayout.setVerticalGroup(
            repFuncDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
            .addGroup(repFuncDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(repFuncDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        repSyntaxErrors.setVisible(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("ERRORES SINTÁCTICOS");

        syntaxErrorsRep.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        syntaxErrorsRep.setForeground(new java.awt.Color(0, 0, 0));
        syntaxErrorsRep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Linea", "Columna", "Detalles"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(syntaxErrorsRep);
        syntaxErrorsRep.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (syntaxErrorsRep.getColumnModel().getColumnCount() > 0) {
            syntaxErrorsRep.getColumnModel().getColumn(0).setMinWidth(60);
            syntaxErrorsRep.getColumnModel().getColumn(0).setPreferredWidth(60);
            syntaxErrorsRep.getColumnModel().getColumn(0).setMaxWidth(10);
            syntaxErrorsRep.getColumnModel().getColumn(1).setMinWidth(60);
            syntaxErrorsRep.getColumnModel().getColumn(1).setPreferredWidth(60);
            syntaxErrorsRep.getColumnModel().getColumn(1).setMaxWidth(10);
        }

        totalSyntaxErrors.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        totalSyntaxErrors.setForeground(new java.awt.Color(0, 0, 0));
        totalSyntaxErrors.setText("0000");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Total de errores:");

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setText("X");
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(totalSyntaxErrors, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(totalSyntaxErrors))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout repSyntaxErrorsLayout = new javax.swing.GroupLayout(repSyntaxErrors.getContentPane());
        repSyntaxErrors.getContentPane().setLayout(repSyntaxErrorsLayout);
        repSyntaxErrorsLayout.setHorizontalGroup(
            repSyntaxErrorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        repSyntaxErrorsLayout.setVerticalGroup(
            repSyntaxErrorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(repSyntaxErrors, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        repLexError.setVisible(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lexErrorRep.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lexErrorRep.setForeground(new java.awt.Color(0, 0, 0));
        lexErrorRep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Linea", "Columna", "Lexema"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(lexErrorRep);
        lexErrorRep.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (lexErrorRep.getColumnModel().getColumnCount() > 0) {
            lexErrorRep.getColumnModel().getColumn(0).setMinWidth(60);
            lexErrorRep.getColumnModel().getColumn(0).setPreferredWidth(60);
            lexErrorRep.getColumnModel().getColumn(0).setMaxWidth(10);
            lexErrorRep.getColumnModel().getColumn(1).setMinWidth(60);
            lexErrorRep.getColumnModel().getColumn(1).setPreferredWidth(60);
            lexErrorRep.getColumnModel().getColumn(1).setMaxWidth(10);
        }

        jLabel6.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("ERRORES LÉXICOS");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Total de errores:");

        totalLexErrrors.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        totalLexErrrors.setForeground(new java.awt.Color(0, 0, 0));
        totalLexErrrors.setText("0000");

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(totalLexErrrors, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(159, 159, 159))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(210, 210, 210)
                        .addComponent(jButton1)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(42, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(totalLexErrrors))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout repLexErrorLayout = new javax.swing.GroupLayout(repLexError.getContentPane());
        repLexError.getContentPane().setLayout(repLexErrorLayout);
        repLexErrorLayout.setHorizontalGroup(
            repLexErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        repLexErrorLayout.setVerticalGroup(
            repLexErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(repLexError, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        repListInstructions.setVisible(true);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Lista de instrucciones");

        listInstRep.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        listInstRep.setForeground(new java.awt.Color(0, 0, 0));
        listInstRep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nivel Identado", "Linea", "Columna", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listInstRep.setColumnSelectionAllowed(true);
        jScrollPane4.setViewportView(listInstRep);
        listInstRep.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (listInstRep.getColumnModel().getColumnCount() > 0) {
            listInstRep.getColumnModel().getColumn(0).setMinWidth(80);
            listInstRep.getColumnModel().getColumn(0).setPreferredWidth(80);
            listInstRep.getColumnModel().getColumn(0).setMaxWidth(80);
            listInstRep.getColumnModel().getColumn(1).setMinWidth(60);
            listInstRep.getColumnModel().getColumn(1).setPreferredWidth(60);
            listInstRep.getColumnModel().getColumn(1).setMaxWidth(10);
            listInstRep.getColumnModel().getColumn(2).setMinWidth(60);
            listInstRep.getColumnModel().getColumn(2).setPreferredWidth(60);
            listInstRep.getColumnModel().getColumn(2).setMaxWidth(10);
        }

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton3.setText("X");
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout repListInstructionsLayout = new javax.swing.GroupLayout(repListInstructions.getContentPane());
        repListInstructions.getContentPane().setLayout(repListInstructionsLayout);
        repListInstructionsLayout.setHorizontalGroup(
            repListInstructionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        repListInstructionsLayout.setVerticalGroup(
            repListInstructionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(repListInstructions, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        repSymbolTBlock.setVisible(true);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Tabla de simbolos por Bloque de Codigo");

        symbolTableBlocks.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        symbolTableBlocks.setForeground(new java.awt.Color(0, 0, 0));
        symbolTableBlocks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Indentacion", "Simbolo", "Tipo", "Valor", "Linea", "Columna"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        symbolTableBlocks.setColumnSelectionAllowed(true);
        jScrollPane6.setViewportView(symbolTableBlocks);
        symbolTableBlocks.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (symbolTableBlocks.getColumnModel().getColumnCount() > 0) {
            symbolTableBlocks.getColumnModel().getColumn(0).setMinWidth(65);
            symbolTableBlocks.getColumnModel().getColumn(0).setPreferredWidth(65);
            symbolTableBlocks.getColumnModel().getColumn(0).setMaxWidth(65);
            symbolTableBlocks.getColumnModel().getColumn(4).setMinWidth(60);
            symbolTableBlocks.getColumnModel().getColumn(4).setPreferredWidth(60);
            symbolTableBlocks.getColumnModel().getColumn(4).setMaxWidth(10);
            symbolTableBlocks.getColumnModel().getColumn(5).setMinWidth(60);
            symbolTableBlocks.getColumnModel().getColumn(5).setPreferredWidth(60);
            symbolTableBlocks.getColumnModel().getColumn(5).setMaxWidth(10);
        }

        bExitSTB.setBackground(new java.awt.Color(255, 0, 0));
        bExitSTB.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bExitSTB.setText("X");
        bExitSTB.setFocusable(false);
        bExitSTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitSTBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bExitSTB))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(bExitSTB)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout repSymbolTBlockLayout = new javax.swing.GroupLayout(repSymbolTBlock.getContentPane());
        repSymbolTBlock.getContentPane().setLayout(repSymbolTBlockLayout);
        repSymbolTBlockLayout.setHorizontalGroup(
            repSymbolTBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        repSymbolTBlockLayout.setVerticalGroup(
            repSymbolTBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(repSymbolTBlock, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        repSymbolT.setVisible(true);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Tabla de simbolos");

        symbolTable.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        symbolTable.setForeground(new java.awt.Color(0, 0, 0));
        symbolTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Simbolo", "Tipo", "Valor", "Linea", "Columna"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        symbolTable.setColumnSelectionAllowed(true);
        jScrollPane5.setViewportView(symbolTable);
        symbolTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (symbolTable.getColumnModel().getColumnCount() > 0) {
            symbolTable.getColumnModel().getColumn(3).setMinWidth(60);
            symbolTable.getColumnModel().getColumn(3).setPreferredWidth(60);
            symbolTable.getColumnModel().getColumn(3).setMaxWidth(10);
            symbolTable.getColumnModel().getColumn(4).setMinWidth(60);
            symbolTable.getColumnModel().getColumn(4).setPreferredWidth(60);
            symbolTable.getColumnModel().getColumn(4).setMaxWidth(10);
        }

        bExitTS.setBackground(new java.awt.Color(255, 0, 0));
        bExitTS.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bExitTS.setText("X");
        bExitTS.setFocusable(false);
        bExitTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitTSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bExitTS))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(bExitTS)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout repSymbolTLayout = new javax.swing.GroupLayout(repSymbolT.getContentPane());
        repSymbolT.getContentPane().setLayout(repSymbolTLayout);
        repSymbolTLayout.setHorizontalGroup(
            repSymbolTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        repSymbolTLayout.setVerticalGroup(
            repSymbolTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(repSymbolT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bTableSimbolBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTableSimbolBActionPerformed
        try {
            reportero.setSymbolTable(symbolTableBlocks, registrador, true);
            this.symbolTableBlocks.setDefaultRenderer(Object.class, new Render());
            ocultar(index);
            mostrar(repSymbolTBlock);
        } catch (SyntaxException e) {
            mostrarMssSyntaxError();
        }
    }//GEN-LAST:event_bTableSimbolBActionPerformed

    private void bAtras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtras1ActionPerformed
        ocultar(repFuncDisplay);
        mostrar(index);
    }//GEN-LAST:event_bAtras1ActionPerformed

    private void bMethodReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMethodReportActionPerformed
        try {
            reportero.setFunctionsRep(funReport, registrador);
            totalFuncDisplay.setText(String.valueOf(registrador.getFunctions().size()));
            ocultar(index);
            mostrar(repFuncDisplay);
        } catch (SyntaxException e) {
            mostrarMssSyntaxError();
        }
    }//GEN-LAST:event_bMethodReportActionPerformed

    private void bAtrasGlobalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtrasGlobalActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_bAtrasGlobalActionPerformed

    private void bSyntaxErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSyntaxErrorActionPerformed
        reportero.setSyntaxErrorRep(syntaxErrorsRep, parser.getErrors());
        totalSyntaxErrors.setText(String.valueOf(parser.getErrors().size()));
        ocultar(index);
        mostrar(repSyntaxErrors);
    }//GEN-LAST:event_bSyntaxErrorActionPerformed

    private void bLexErrorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLexErrorsActionPerformed
        reportero.setLexErrorRep(lexErrorRep, lexer.getErrors());
        totalLexErrrors.setText(String.valueOf(lexer.getErrors().size()));
        ocultar(index);
        mostrar(repLexError);
    }//GEN-LAST:event_bLexErrorsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ocultar(repLexError);
        mostrar(index);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ocultar(repSyntaxErrors);
        mostrar(index);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ocultar(repListInstructions);
        mostrar(index);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void bInstructionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInstructionsActionPerformed
        try {
            reportero.setListInstRep(listInstRep, registrador);	
            this.listInstRep.setDefaultRenderer(Object.class, new Render());
            ocultar(index);
            mostrar(repListInstructions);
        } catch (SyntaxException e) {
            mostrarMssSyntaxError();
        }
    }//GEN-LAST:event_bInstructionsActionPerformed

    private void bExitTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitTSActionPerformed
        ocultar(repSymbolT);
        mostrar(index);
    }//GEN-LAST:event_bExitTSActionPerformed

    private void bExitSTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitSTBActionPerformed
        ocultar(repSymbolTBlock);
        mostrar(index);
    }//GEN-LAST:event_bExitSTBActionPerformed

    private void bTableSymbolGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTableSymbolGActionPerformed
        try {
            reportero.setSymbolTable(symbolTable, registrador, false);
            ocultar(index);
            mostrar(repSymbolT);
        } catch (SyntaxException e) {
            mostrarMssSyntaxError();
        }
    }//GEN-LAST:event_bTableSymbolGActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAtras1;
    private javax.swing.JButton bAtrasGlobal;
    private javax.swing.JButton bExitSTB;
    private javax.swing.JButton bExitTS;
    private javax.swing.JButton bInstructions;
    private javax.swing.JButton bLexErrors;
    private javax.swing.JButton bMethodReport;
    private javax.swing.JButton bSyntaxError;
    private javax.swing.JButton bTableSimbolB;
    private javax.swing.JButton bTableSymbolG;
    private javax.swing.JTable funReport;
    private javax.swing.JInternalFrame index;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable lexErrorRep;
    private javax.swing.JTable listInstRep;
    private javax.swing.JPanel panel;
    private javax.swing.JInternalFrame repFuncDisplay;
    private javax.swing.JInternalFrame repLexError;
    private javax.swing.JInternalFrame repListInstructions;
    private javax.swing.JInternalFrame repSymbolT;
    private javax.swing.JInternalFrame repSymbolTBlock;
    private javax.swing.JInternalFrame repSyntaxErrors;
    private javax.swing.JTable symbolTable;
    private javax.swing.JTable symbolTableBlocks;
    private javax.swing.JTable syntaxErrorsRep;
    private javax.swing.JLabel totalFuncDisplay;
    private javax.swing.JLabel totalLexErrrors;
    private javax.swing.JLabel totalSyntaxErrors;
    // End of variables declaration//GEN-END:variables
}
